# branding.py
"""
Dynamic report branding.
Default is Datazag. Override per-report for white-label customers.

Usage:
    brand = BrandConfig.load()                    # Datazag default
    brand = BrandConfig.load("mssp_partner")      # from brands/mssp_partner.json
    brand = BrandConfig.from_env()                # from environment variables
"""

from __future__ import annotations

import json
import os
from dataclasses import dataclass, field
from pathlib import Path
from typing import Optional


@dataclass
class BrandConfig:
    # Identity
    brand_name: str         = "Datazag"
    brand_tagline: str      = "Infrastructure Intelligence"
    brand_url: str          = "https://datazag.com"

    # Colours — all hex
    primary_colour: str     = "#0F1923"    # Dark navy — header bg
    accent_colour: str      = "#00C2FF"    # Cyan — highlights
    accent_dark: str        = "#0096CC"    # Darker cyan for hover
    text_on_primary: str    = "#FFFFFF"
    text_on_accent: str     = "#003344"

    # Logo — inline SVG string or None (falls back to text wordmark)
    logo_svg: Optional[str] = None

    # Contact block
    contact_email: str      = "intelligence@datazag.com"
    contact_phone: str      = ""
    contact_web: str        = "https://datazag.com"
    contact_address: str    = "Datazag Ltd · United Kingdom"

    # Report framing
    report_prefix: str      = "Datazag Intelligence Report"
    report_footer: str      = (
        "This report was generated by Datazag's automated DNS intelligence platform. "
        "Data is collected passively from public DNS infrastructure. "
        "Datazag Limited is registered in England and Wales."
    )
    confidentiality_notice: str = (
        "CONFIDENTIAL — This report is prepared exclusively for the named recipient. "
        "Redistribution without written consent is prohibited."
    )

    # CTA block
    cta_heading: str        = "Want to monitor this domain continuously?"
    cta_body: str           = (
        "Datazag monitors over 320 million domains in real time. "
        "Get alerts when DNS records change, new subdomains appear, "
        "or threat scores shift — before your customers notice."
    )
    cta_button_text: str    = "Request a demo"
    cta_button_url: str     = "https://datazag.com/demo"
    cta_secondary_text: str = "Or email us at"
    cta_secondary_url: str  = "mailto:intelligence@datazag.com"

    # White-label flag — suppresses Datazag references in footer
    is_white_label: bool    = False
    powered_by_text: str    = ""    # e.g. "Powered by Datazag" if customer allows

    @classmethod
    def default(cls) -> "BrandConfig":
        return cls()

    @classmethod
    def from_env(cls) -> "BrandConfig":
        """Load from environment variables — useful for CI/CD and Docker."""
        return cls(
            brand_name=os.environ.get("BRAND_NAME", "Datazag"),
            brand_tagline=os.environ.get("BRAND_TAGLINE", "Infrastructure Intelligence"),
            brand_url=os.environ.get("BRAND_URL", "https://datazag.com"),
            primary_colour=os.environ.get("BRAND_PRIMARY", "#0F1923"),
            accent_colour=os.environ.get("BRAND_ACCENT", "#00C2FF"),
            accent_dark=os.environ.get("BRAND_ACCENT_DARK", "#0096CC"),
            contact_email=os.environ.get("BRAND_EMAIL", "intelligence@datazag.com"),
            contact_phone=os.environ.get("BRAND_PHONE", ""),
            contact_web=os.environ.get("BRAND_WEB", "https://datazag.com"),
            contact_address=os.environ.get("BRAND_ADDRESS", "Datazag Ltd · United Kingdom"),
            report_prefix=os.environ.get("BRAND_REPORT_PREFIX", "Datazag Intelligence Report"),
            cta_button_url=os.environ.get("BRAND_CTA_URL", "https://datazag.com/demo"),
            cta_button_text=os.environ.get("BRAND_CTA_TEXT", "Request a demo"),
            cta_heading=os.environ.get("BRAND_CTA_HEADING", "Want to monitor this domain continuously?"),
            is_white_label=os.environ.get("BRAND_WHITE_LABEL", "").lower() == "true",
            powered_by_text=os.environ.get("BRAND_POWERED_BY", ""),
            logo_svg=os.environ.get("BRAND_LOGO_SVG"),
        )

    @classmethod
    def load(cls, profile: Optional[str] = None) -> "BrandConfig":
        """
        Load a named brand profile from brands/<profile>.json.
        Falls back to default Datazag if file not found.
        """
        if not profile:
            return cls.from_env() if os.environ.get("BRAND_NAME") else cls.default()

        brands_dir = Path(__file__).parent / "brands"
        brand_file = brands_dir / f"{profile}.json"

        if not brand_file.exists():
            print(f"  Warning: brand profile '{profile}' not found, using default")
            return cls.default()

        with open(brand_file) as f:
            data = json.load(f)

        return cls(**{k: v for k, v in data.items() if k in cls.__dataclass_fields__})

    def save(self, profile: str):
        """Save this config as a named brand profile."""
        brands_dir = Path(__file__).parent / "brands"
        brands_dir.mkdir(exist_ok=True)
        with open(brands_dir / f"{profile}.json", "w") as f:
            json.dump(self.__dict__, f, indent=2)
        print(f"  Brand profile saved to brands/{profile}.json")

    def wordmark_svg(self, height: int = 32) -> str:
        """
        Returns either the custom logo SVG or a generated text wordmark.
        Always returns an inline SVG string.
        """
        if self.logo_svg:
            return self.logo_svg

        # Generated wordmark — brand name in accent colour
        width = len(self.brand_name) * 14 + 20
        return f"""<svg height="{height}" viewBox="0 0 {width} {height}"
            xmlns="http://www.w3.org/2000/svg">
          <text x="10" y="{height * 0.72:.0f}"
            font-family="-apple-system,BlinkMacSystemFont,'Segoe UI',sans-serif"
            font-size="{height * 0.65:.0f}"
            font-weight="700"
            letter-spacing="-0.5"
            fill="{self.accent_colour}">{self.brand_name}</text>
        </svg>"""