"""WU21 design-token generator.

`design/tokens.json` is the only hand-edited style-constant file. This script
generates every downstream artefact; run with --check in CI/pre-commit to fail
the build if a generated file is stale or was hand-edited.

Targets (all under design/generated/):
  tokens.css        -> marketing site global stylesheet import
  tailwind.tokens.js-> portal Tailwind theme.extend fragment
  _tokens.css.j2    -> Jinja include for the report renderers
  tokens.py         -> Python constants + CSS_ROOT for the report renderers
"""
from __future__ import annotations

import json
import sys
from pathlib import Path

DESIGN_DIR = Path(__file__).resolve().parent
TOKENS_JSON = DESIGN_DIR / "tokens.json"
GENERATED_DIR = DESIGN_DIR / "generated"

HEADER = "GENERATED by design/generate_tokens.py from design/tokens.json - do not hand-edit."


def _load() -> dict:
    with open(TOKENS_JSON, encoding="utf-8") as f:
        return json.load(f)


def _family(name: str) -> str:
    return name.split("-")[0]


def _css_root(colors: dict[str, str]) -> str:
    """The :root block shared by every CSS surface, one line per colour family."""
    lines: list[str] = []
    current_family = None
    line: list[str] = []
    for name, value in colors.items():
        fam = _family(name)
        if fam != current_family and line:
            lines.append("  " + "".join(line))
            line = []
        current_family = fam
        line.append(f"--{name}:{value};")
    if line:
        lines.append("  " + "".join(line))
    return ":root{\n" + "\n".join(lines) + "\n}"


def _resolve(colors: dict[str, str], ref: str) -> str:
    """A semantic entry is either a colour name or a literal value."""
    return colors.get(ref, ref)


def _semantic_flat(tokens: dict) -> dict[str, str]:
    """Flat --<group>-<key> custom-property map with resolved colour values."""
    colors = tokens["color"]
    out: dict[str, str] = {}
    for group, entries in tokens["semantic"].items():
        for key, ref in entries.items():
            out[f"{group}-{key.lower()}"] = _resolve(colors, ref)
    return out


def gen_tokens_css(tokens: dict) -> str:
    semantic = _semantic_flat(tokens)
    sem_lines = "\n".join(f"  --{name}:{value};" for name, value in semantic.items())
    root = _css_root(tokens["color"])
    # Splice semantic vars into the same :root so the site imports one block.
    root_open, root_body_close = root.split("\n", 1)
    return (
        f"/* {HEADER} */\n"
        + root_open + "\n"
        + root_body_close.removesuffix("\n}")
        + "\n" + sem_lines + "\n}\n"
    )


def gen_tokens_css_j2(tokens: dict) -> str:
    return f"/* {HEADER} */\n" + _css_root(tokens["color"]) + "\n"


def gen_tailwind(tokens: dict) -> str:
    colors = tokens["color"]
    semantic = {
        group: {key: _resolve(colors, ref) for key, ref in entries.items()}
        for group, entries in tokens["semantic"].items()
    }
    fragment = {
        "colors": colors,
        "fontFamily": {
            "sans": [part.strip() for part in tokens["font"]["sans"].split(",")],
            "mono": [part.strip() for part in tokens["font"]["mono"].split(",")],
        },
        "borderRadius": tokens["radius"],
        "semantic": semantic,
    }
    body = json.dumps(fragment, indent=2)
    return f"// {HEADER}\nmodule.exports = {body};\n"


def gen_tokens_py(tokens: dict) -> str:
    colors = tokens["color"]
    semantic = {
        group: {key: _resolve(colors, ref) for key, ref in entries.items()}
        for group, entries in tokens["semantic"].items()
    }
    css_root = _css_root(colors)

    def fmt(obj: dict) -> str:
        return json.dumps(obj, indent=4)

    return (
        f'"""{HEADER}"""\n\n'
        f"COLORS = {fmt(colors)}\n\n"
        f"FONTS = {fmt(tokens['font'])}\n\n"
        f"RADIUS = {fmt(tokens['radius'])}\n\n"
        f"SEVERITY = {fmt(semantic['severity'])}\n\n"
        f"PRIORITY = {fmt(semantic['priority'])}\n\n"
        f"TIER = {fmt(semantic['tier'])}\n\n"
        f"GRADE = {fmt(semantic['grade'])}\n\n"
        f'CSS_ROOT = """{css_root}"""\n'
    )


TARGETS = {
    "tokens.css": gen_tokens_css,
    "tailwind.tokens.js": gen_tailwind,
    "_tokens.css.j2": gen_tokens_css_j2,
    "tokens.py": gen_tokens_py,
}


def build() -> dict[str, str]:
    tokens = _load()
    return {name: fn(tokens) for name, fn in TARGETS.items()}


def main() -> int:
    check = "--check" in sys.argv
    outputs = build()
    stale: list[str] = []
    GENERATED_DIR.mkdir(exist_ok=True)
    for name, content in outputs.items():
        path = GENERATED_DIR / name
        if check:
            on_disk = path.read_text(encoding="utf-8") if path.exists() else None
            if on_disk != content:
                stale.append(name)
        else:
            path.write_text(content, encoding="utf-8", newline="\n")
    if check and stale:
        print(f"Design tokens drift: stale or hand-edited generated files: {', '.join(stale)}")
        print("Run: python design/generate_tokens.py")
        return 1
    if not check:
        print(f"Generated {len(outputs)} files in {GENERATED_DIR}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
